site_name: PlotlyJS.jl
# site_url: http://www.mkdocs.org
site_description: Julia + plotly.js
site_author: Spencer Lyon
theme: material

repo_url: https://github.com/spencerlyon2/PlotlyJS.jl

pages:
- Home: index.md
- User Guide:
    - Preliminaries: basics.md
    - Building Blocks: building_traces_layouts.md
    - Putting it together: syncplots.md
#     - Deploying Your Docs: user-guide/deploying-your-docs.md
#     - Custom Themes: user-guide/custom-themes.md
# - About:
#     - Release Notes: about/release-notes.md
#     - Contributing: about/contributing.md
#     - License: about/license.md

markdown_extensions:
    - codehilite
#     - toc:
#         permalink: 
#     - admonition:

extra_css: [css/github.css]
extra_javascript: ["https://cdn.plot.ly/plotly-latest.min.js"]

copyright: Copyright &copy; 2016 <a href="http://spencerlyon.com/">Spencer Lyon</a>
# google_analytics: ['UA-27795084-5', 'mkdocs.org']
